
server:
  port: 8090

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: microservicio-gateway

  cloud:
    gateway:
      routes:
        - id: microservicio-activo-personal
          predicates: Path=/api/activo/personal/**
          filters: StripPrefix=3
          uri: lb://microservicio-activo-personal
   
        - id: microservicio-activo-empresarial
          predicates: Path=/api/activo/empresarial/**
          filters: StripPrefix=3
          uri: lb://microservicio-activo-empresarial
    
        - filters: StripPrefix=4
          predicates: Path=/api/activo/tarjeta/credito/**
          id: microservicio-activo-tarjetadecredito
          uri: lb://microservicio-activo-tarjetadecredito
  
        - predicates: Path=/api/cargar/credito/**
          id: microservicio-cargar-credito
          uri: lb://microservicio-cargar-credito
          filters: StripPrefix=3
    
        - uri: lb://microservicio-cuenta-activa
          predicates: Path=/api/cuenta/activa/**
          id: microservicio-cuenta-activa
          filters: StripPrefix=3
  
        - uri: lb://microservicio-cuenta-pasiva
          filters: StripPrefix=3
          predicates: Path=/api/cuenta/pasiva/**
          id: microservicio-cuenta-pasiva
     
        - id: microservicio-cliente-juridico
          uri: lb://microservicio-cliente-juridico
          predicates: Path=/api/cliente/juridico/**
          filters: StripPrefix=3
     
        - predicates: Path=/api/cliente/natural/**
          filters: StripPrefix=3
          uri: lb://microservicio-cliente-natural
          id: microservicio-cliente-natural
   
        - predicates: Path=/api/deposito/cuenta/**
          uri: lb://microservicio-deposito-cuentas
          id: microservicio-deposito-cuentas
          filters: StripPrefix=3
 
        - predicates: Path=/api/empresarial/cuentacorriente/**
          id: microservicio-empresarial-cuentacorriente
          filters: StripPrefix=3
          uri: lb://microservicio-empresarial-cuentacorriente

        - predicates: Path=/api/movimiento/cuentas/**
          uri: lb://microservicio-movimiento-cuentas
          id: microservicio-movimiento-cuentas
          filters: StripPrefix=3
  
        - predicates: Path=/api/pagos/credito/**
          filters: StripPrefix=3
          id: microservicio-pagos-credito
          uri: lb://microservicio-pagos-credito
     
        - predicates: Path=/api/pasivo/ahorro/**
          uri: lb://microservicio-pasivo-ahorro
          filters: StripPrefix=3
          id: microservicio-pasivo-ahorro
  
        - predicates: Path=/api/pasivo/cuentacorriente/**
          uri: lb://microservicio-pasivo-cuentacorriente
          filters: StripPrefix=3
          id: microservicio-pasivo-cuentacorriente
 
        - predicates: Path=/api/pasivo/plazofijo/**
          id: microservicio-pasivo-plazofijo
          filters: StripPrefix=3
          uri: lb://microservicio-pasivo-plazofijo

        - predicates: Path=/api/persona/cuenta/pasiva/**
          id: microservicio-persona-cuenta-pasiva
          uri: lb://microservicio-persona-cuenta-pasiva
          filters: StripPrefix=4
    
        - filters: StripPrefix=3
          predicates: Path=/api/representante/empresarial/**
          id: microservicio-representante-empresarial
          uri: lb://microservicio-representante-empresarial
 
        - id: microservicio-retiros-cuentas
          filters: StripPrefix=3
          uri: lb://microservicio-retiros-cuentas
          predicates: Path=/api/retiros/cuenta/**

        - id: microservicio-saldo-cuenta
          uri: lb://microservicio-saldo-cuenta
          filters: StripPrefix=3
          predicates: Path=/api/saldo/cuenta/**
      
        - filters: StripPrefix=3
          id: microservicio-usar-cuenta
          uri: lb://microservicio-usar-cuenta
          predicates: Path=/api/usar/cuenta/**
   
        - filters: StripPrefix=3
          id: microservicio-tarjeta-debito
          uri: lb://microservicio-tarjeta-debito
          predicates: Path=/api/tarjeta/debito/**
   
        - filters: StripPrefix=3
          id: microservicio-bootcoin-currency
          uri: lb://microservicio-bootcoin-currency
          predicates: Path=/api/bootcoin/currency/**

        - filters: StripPrefix=3
          id: microservicio-yanki-wallet
          uri: lb://microservicio-yanki-wallet
          predicates: Path=/api/yanki/wallet/**




      discovery:
        locator:
          enabled: 'true'
    loadbalancer:
      ribbon:
        enabled: 'false'
 
  kafka:
    bootstrap-servers: localhost:9092
  redis:
        url: redis://localhost:6379




  
